// @maple-dev/effect-orm/clickhouse
//
// Everything for ClickHouse from one import: column types, tables with their
// DDL, the function catalog, the query builder and `compile`. Postgres has the
// same shape under `/postgres`. See docs/getting-started.md.

export * from "./core"

// Column Types
export {
	type CHString,
	type CHUInt8,
	type CHUInt16,
	type CHUInt32,
	type CHInt32,
	type CHInt64,
	type CHBool,
	type CHUInt64,
	type CHFloat64,
	type CHDateTime,
	type CHDateTimeString,
	type CHDateTime64String,
	type CHDateTime64,
	type CHMap,
	type CHArray,
	type CHNullable,
	type CHStringLike,
	CHNumber,
	string,
	uint8,
	uint16,
	uint32,
	bool,
	uint64,
	int32,
	int64,
	float64,
	aggregateState,
	untyped,
	dateTime,
	dateTime64,
	dateTimeString,
	dateTime64String,
	map,
	array,
	nullable,
	lowCardinality,
	simpleAggregateFunction,
	precision,
	custom,
	brand,
} from "./ch/types"

// Tables, materialized views and their DDL. `table` is the only way to declare
// a table: it carries the engine and keys `effect-orm generate` diffs.
export {
	defineTable as table,
	column,
	engine,
	index,
	materializedView,
	ttlAfterDays,
	SchemaDefinitionDefect,
	type ColumnInput,
	type ColumnOptions,
	type ColumnSpec,
	type ColumnsOf,
	type ComputedColumnsOf,
	type DefaultedColumnsOf,
	type DdlExpr,
	type DdlKey,
	type IndexSpec,
	type MaterializedView,
	type MisfitColumns,
	type SchemaTable,
	type TableDdl,
	type TableDefinition,
	type ExternalTableDefinition,
} from "./schema/define"

// ClickHouse functions (from category modules)
export {
	// Aggregate
	count,
	countIf,
	avg,
	sum,
	min_ as min,
	max_ as max,
	quantile,
	any_ as any,
	anyIf,
	uniq,
	uniqIf,
	uniqExact,
	sumIf,
	avgIf,
	maxIf,
	minIf,
	groupUniqArray,
	groupUniqArrayArray,
	groupUniqArrayIf,
	argMin,
	argMax,
	argMaxMerge,
	windowFunnel,
	sequenceMatch,
	type WindowFunnelMode,
	// String
	toString_ as toString,
	positionCaseInsensitive,
	position_ as position,
	left_ as left,
	length_ as length,
	lower_ as lower,
	domain_ as domain,
	hex,
	path_ as path,
	cutQueryString,
	replaceOne,
	extract_ as extract,
	match_ as match,
	matchCond,
	concat,
	hasToken,
	hasAllTokens,
	// Numeric
	round_ as round,
	intDiv,
	toFloat64OrZero,
	toFloat64,
	toUInt16OrZero,
	toUInt64,
	toInt64,
	least_ as least,
	greatest_ as greatest,
	cityHash64,
	// Date/time
	toStartOfInterval,
	toStartOfHour,
	toStartOfMinute,
	toHour,
	toUnixTimestamp,
	toUnixTimestamp64Nano,
	intervalAdd,
	intervalSub,
	formatDateTime,
	toDateTime,
	// Conditional
	if_,
	multiIf,
	coalesce,
	ifNull,
	nullIf,
	ifNotFinite,
	// Array
	arrayOf,
	arrayStringConcat,
	arrayFilter,
	arrayDistinct,
	arrayElement,
	arrayJoin,
	arrayPushFront,
	arrayReverseSort,
	arraySort,
	has,
	// Map
	mapContains,
	mapGet,
	mapKeys,
	mapValues,
	mapLiteral,
	// JSON
	toJSONString,
	// Window
	currentRow,
	unboundedPreceding,
	unboundedFollowing,
	preceding,
	following,
	rowsBetween,
	windowSpec,
	over,
	lagInFrame,
	type CompiledWindowSpec,
	type WindowFrameBound,
	type WindowOrderDirection,
	type WindowRowsFrame,
	type WindowSpec,
} from "./ch/functions"

// Compilation, defaulting to the ClickHouse dialect
export { compileCH as compile, compileCHUnsafe as compileUnsafe, compileUnion, compileUnionUnsafe } from "./ch/compile"
export { clickhouseDialect } from "./ch/dialect"
